import { Inter } from "next/font/google";
import local from "next/font/local";
import "./globals.css";
import "rodal/lib/rodal.css";

const kalpurush = local({
  src: "../fonts/kalpurush.ttf",
  variable: "--kalpurush",
});

const kfgq = local({
  src: "../fonts/KFGQPC.otf",
  variable: "--kfgq",
});

const inter = Inter({ subsets: ["latin"], variable: "--inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kalpurush.variable} ${inter.variable} ${kfgq.variable} font-kalpurush`}
      >
        {children}
      </body>
    </html>
  );
}
